#### Workflow for B -> J/psi eta  analysis
## Author: Colm Murphy
## Institute: IPMU
## Email: colm.murphy@ipmu.jp
## Repository: https://github.com/chm-ipmu/belle2

configfile: "snakemake_config/b2jpsi_eta.yaml"

# EvtGen --> GSIM --> hadd
# Makes DECAYS variable available.
include: "../snakefiles/produce_mc.snake"

rule all:
    input: expand("simulation/root_files/merged/{decay}.root", decay=DECAYS)
